spring.application.name=ShopingBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/shopping
spring.datasource.username=postgres
spring.datasource.password=nikO_151622

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nurimuhammad7473@gmail.com
spring.mail.password=nmia wzai hofk fqpa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true